🔧 Refactor maven.yml to update Test Reporter path for diagnostic app and build Docker image instead of restarting Docker Compose

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -1,4 +1,4 @@
-name: Quarkus CI/CD Pipeline
+name: Quarkus CI with Docker
 
 on:
   push:
@@ -6,13 +6,15 @@ on:
   pull_request_target:
     branches: ["master", "develop"]
   schedule:
-    - cron: "0 7 * * *" # Daily at 7:00 AM
+    - cron: "0 7 * * *"
+    # Schedule: Run every day at 7:00 AM
 
 jobs:
   build-and-test:
     runs-on: ubuntu-latest
     environment: staging
     env:
+      WORDSAPI_KEY: ${{ secrets.WORDSAPI_KEY }}
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
     services:
@@ -33,8 +35,8 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        language: ["java"]
-
+        language: ["java-kotlin"]
+   
     steps:
       - name: Set up JDK 21
         uses: actions/setup-java@v4
@@ -45,6 +47,11 @@ jobs:
       - name: Checkout Code
         uses: actions/checkout@v4
 
+      - name: Debug Environment Variables
+        run: |
+          echo "WORDSAPI_KEY: $WORDSAPI_KEY"
+          echo "GITHUB_TOKEN: $GITHUB_TOKEN"
+      
       - name: Build and Test with Maven
         run: mvn verify
 
@@ -62,7 +69,7 @@ jobs:
     needs: build-and-test
     runs-on: ubuntu-latest
     if: github.event_name == 'push' && github.ref == 'refs/heads/master'
-    environment: production
+    environment: staging
     
     env:
       PUBLIC_IP: ${{ secrets.PUBLIC_IP }}
@@ -77,8 +84,14 @@ jobs:
           mkdir -p ~/.ssh
           echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
           chmod 600 ~/.ssh/id_rsa
+          
+      - name: Debug Environment Variables
+        run: |
+          echo "PUBLIC_IP: $PUBLIC_IP"
+          echo "PI_USERNAME: $PI_USERNAME"
 
       - name: SSH to Raspberry Pi and Deploy Changes
+        id: ssh_pull
         uses: appleboy/ssh-action@master
         with:
           host: ${{ secrets.PUBLIC_IP }}
@@ -89,6 +102,26 @@ jobs:
             cd dev/projects/tadiag
             git reset --hard origin/master
             git pull origin master
-            ./mvnw package
+        continue-on-error: true
+
+      - name: Check if git pull was successful
+        if: steps.ssh_pull.outcome == 'failure'
+        run: exit 1 # Fail the workflow if git pull failed
+
+      - name: SSH to Raspberry Pi and build Docker image
+        id: ssh_build
+        uses: appleboy/ssh-action@master
+        with:
+          host: ${{ secrets.PUBLIC_IP }}
+          username: ${{ secrets.PI_USERNAME }}
+          key: ${{ secrets.SSH_PRIVATE_KEY }}
+          script: |
+            cd dev/projects/tadiag
+             ./mvnw package
             docker build -f src/main/docker/Dockerfile.jvm -t quarkus/tadiag-jvm .
             docker run --name tadiag --env-file .env.prod -i --rm -p 8083:8080 quarkus/tadiag-jvm
+        continue-on-error: true
+
+      - name: Check if Docker Compose restart was successful
+        if: steps.ssh_build.outcome == 'failure'
+        run: exit 1 # Fail the workflow if Docker Compose restart failed
